name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m unittest discover .

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image locally
      run: |
        docker build -t python-k8s-app:latest .
        echo "✅ Docker image built successfully"
        
    - name: Show local deployment info
      run: |
        echo "🚀 Image built locally for manual deployment"
        echo ""
        echo "To deploy to your local Kubernetes:"
        echo "1. Build image locally: docker build -t python-k8s-app:latest ."
        echo "2. Apply deployment: kubectl apply -f k8s/deployment.yaml"
        echo "3. Apply service: kubectl apply -f k8s/service.yaml"
        echo "4. Check status: kubectl get pods -l app=python-calculator"
        echo "5. Test app: curl http://localhost:30080/health"